# Generated by Django 5.2.5 on 2025-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('items', models.JSONField()),
                ('sub_total', models.FloatField()),
                ('gst_total', models.FloatField()),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
